### ISSUE TITLE
Page Size & Page Speed: Did not passed. 65 is the passing score for page speed and and 2mb for the page size

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Cut-Above-Events#128]
![image](https://cloud.githubusercontent.com/assets/13363508/13138019/aacd0042-d65f-11e5-8c58-dba73024eb1c.png)
![image](https://cloud.githubusercontent.com/assets/13363508/13138032/b6175380-d65f-11e5-901a-c165525e764e.png)

**Comment by nakul-titan** [comment]
It is due to large image size I have tried reducing size of images but still single image occupying 1.25MB size.
