### ISSUE TITLE
General - Inner Pages: Page Title and subheading are not following the scope instructions. Some are interchange and some are being hard-coded

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Cut-Above-Events#91]
H1 header should be 16px while the subheading should be 32px 
![image](https://cloud.githubusercontent.com/assets/13363508/12938294/b56eef7a-cfec-11e5-9c2f-7ff82e25a93c.png)

![image](https://cloud.githubusercontent.com/assets/13363508/12937415/4e7eb8c6-cfe3-11e5-9308-dcac2f1ceaff.png)

**Comment by nakul-titan** [comment]
Scope has been updated.

**Comment by maehtitan** [comment]
@nakul-titan Still not right, main title page means it is the first title located at the very top of the page and it should be the <h1> even if the font color 14px and then the sub-heading followed, I believe this is the right implementation coz try to observe the sitemap, can you spot where is the contact us, services, gallery and etc using the subheading? It's really hard, you need go through that page and double check if that's really the right page your looking for. I hope you understand the scenario.
![image](https://cloud.githubusercontent.com/assets/13363508/13101264/e915ca22-d57f-11e5-96fa-1dad316ee8a1.png)
